"""Shared test plumbing.

PROVIDED INFRASTRUCTURE. Do not edit this file.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# A tiny open room. Pac-Man starts at (2, 2) with room to move in every
# direction, which keeps most tests independent of the real maze.
TEST_LEVEL = (
    "#####",
    "#...#",
    "#.P.#",
    "#...#",
    "#####",
)


def load_module(filename: str):
    """Import a project-root file fresh, under its own natural module name.

    Some of the six files import each other (``learning_agent.py`` imports
    from ``utility_based_agent.py``), and Python resolves those inner
    imports by the plain module name -- so this loader always registers a
    module under its filename stem (``utility_based_agent.py`` ->
    ``utility_based_agent``), the same name any other file's ``import``
    statement would look for. It also drops any previously cached module of
    that name first, which matters if you re-run tests after editing a
    file mid-session.
    """
    module_name = filename[:-3] if filename.endswith(".py") else filename
    path = PROJECT_ROOT / filename
    sys.modules.pop(module_name, None)

    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec and spec.loader, f"could not load {path}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module
