"""Scope and integrity checks, shared across all six parts.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_scope -v
"""

from __future__ import annotations

import inspect
import re
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _helpers import PROJECT_ROOT, load_module  # noqa: E402

PARTS = {
    "table_driven": ("table_driven_agent.py", "TableDrivenAgent"),
    "simple_reflex": ("simple_reflex_agent.py", "SimpleReflexAgent"),
    "model_based": ("model_based_agent.py", "ModelBasedAgent"),
    "goal_based": ("goal_based_agent.py", "GoalBasedAgent"),
    "utility_based": ("utility_based_agent.py", "UtilityBasedAgent"),
    "learning": ("learning_agent.py", "LearningAgent"),
}

FORBIDDEN_ENVIRONMENT_ACCESS = (
    "pacman.rules",
    "pacman.render",
    "pacman.entities",
    "pacman.headless",
    "Simulation",
)

FORBIDDEN_SEARCH = ("import heapq", "PriorityQueue", "def a_star", "def astar")


def _source(filename: str) -> str:
    return (PROJECT_ROOT / filename).read_text(encoding="utf-8")


class TestScope(unittest.TestCase):
    def test_every_part_file_exists_and_defines_its_class(self):
        for part, (filename, class_name) in PARTS.items():
            with self.subTest(part=part):
                path = PROJECT_ROOT / filename
                self.assertTrue(path.exists(), f"{filename} is missing.")
                module = load_module(filename)
                self.assertTrue(
                    hasattr(module, class_name),
                    f"{filename} does not define {class_name}.",
                )

    def test_no_part_touches_the_live_environment(self):
        for part, (filename, _) in PARTS.items():
            with self.subTest(part=part):
                source = _source(filename)
                for forbidden in FORBIDDEN_ENVIRONMENT_ACCESS:
                    self.assertNotIn(
                        forbidden,
                        source,
                        f"{filename} references {forbidden!r}. Every agent "
                        "may only use its percept and the static MazeModel.",
                    )

    def test_no_part_implements_its_own_search(self):
        for part, (filename, _) in PARTS.items():
            with self.subTest(part=part):
                source = _source(filename)
                for forbidden in FORBIDDEN_SEARCH:
                    self.assertNotIn(
                        forbidden,
                        source,
                        f"{filename} contains {forbidden!r}. Search "
                        "algorithms are Chapter 3 -- use self.maze.distance.",
                    )

    def test_no_todo_markers_remain(self):
        for part, (filename, _) in PARTS.items():
            with self.subTest(part=part):
                remaining = sorted(
                    set(re.findall(r"TODO\(CH2-[\w-]+\)", _source(filename)))
                )
                self.assertFalse(
                    remaining,
                    f"{filename} still has unfinished markers: {remaining}.",
                )

    def test_no_part_edits_the_pacman_package(self):
        """This test cannot see what you changed, only that you did not
        submit an edited copy of pacman/ alongside your six files -- the
        real check happens when the grader runs your files against a
        clean pacman/ package. Treat a failure here as a reminder, not the
        whole story."""
        pacman_dir = PROJECT_ROOT / "pacman"
        self.assertTrue(pacman_dir.exists(), "pacman/ package is missing.")

    def test_percept_class_attribute_matches_the_declared_percept(self):
        for part, (filename, class_name) in PARTS.items():
            with self.subTest(part=part):
                module = load_module(filename)
                agent_class = getattr(module, class_name)
                self.assertTrue(
                    hasattr(module, "Percept") or part == "learning",
                    f"{filename} should define a Percept dataclass.",
                )
                self.assertTrue(
                    hasattr(agent_class, "percept_class"),
                    f"{class_name} must expose a percept_class attribute.",
                )


if __name__ == "__main__":
    unittest.main()
