"""Part 1 - Table-driven agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part1_table_driven -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

from _helpers import load_module  # noqa: E402

AGENT_FILE = "table_driven_agent.py"


class TestPart1TableDriven(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_module(AGENT_FILE)

    def new_agent(self):
        from pacman.maze import MazeModel

        return self.module.TableDrivenAgent(MazeModel())

    def test_percept_declares_only_current_direction_and_legal_actions(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        self.assertEqual(
            declared,
            {"current_direction", "legal_actions"},
            "Part 1: Percept should declare exactly current_direction and "
            "legal_actions -- nothing more. A bigger percept makes the "
            "table too big to build by hand, which is the whole point.",
        )

    def test_percept_fields_are_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(unknown, f"Part 1: unknown percept field(s) {unknown}")

    def test_agent_exposes_its_percept_class(self):
        agent = self.new_agent()
        self.assertIs(agent.percept_class, self.module.Percept)

    def test_table_is_built_in_init_not_on_the_fly(self):
        agent = self.new_agent()
        self.assertTrue(
            hasattr(agent, "table"),
            "Part 1: expected a `table` attribute built in __init__.",
        )
        self.assertGreater(
            len(agent.table),
            10,
            "Part 1: the table should already hold many entries right "
            "after construction, before choose_action is ever called.",
        )

    def test_choose_action_always_returns_a_legal_action(self):
        agent = self.new_agent()
        cases = [
            (DIRECTIONS["LEFT"], (DIRECTIONS["LEFT"], DIRECTIONS["RIGHT"])),
            (DIRECTIONS["UP"], (DIRECTIONS["UP"], DIRECTIONS["DOWN"])),
            ((0, 0), tuple(DIRECTIONS.values())),
            (DIRECTIONS["DOWN"], (DIRECTIONS["LEFT"],)),
        ]
        for current_direction, legal in cases:
            percept = self.module.Percept(
                current_direction=current_direction, legal_actions=legal
            )
            action = agent.choose_action(percept)
            self.assertIn(action, legal)

    def test_no_legal_actions_is_handled(self):
        agent = self.new_agent()
        percept = self.module.Percept(current_direction=(0, 0), legal_actions=())
        self.assertEqual(agent.choose_action(percept), (0, 0))
        self.assertIn("No legal", agent.last_reason)

    def test_a_missing_table_entry_still_returns_a_legal_action(self):
        """A table-driven agent cannot enumerate every percept sequence.
        When yours is asked about one it has no entry for, it must still
        respond with something legal instead of raising."""
        agent = self.new_agent()
        legal = (DIRECTIONS["LEFT"], DIRECTIONS["RIGHT"])
        key = (DIRECTIONS["UP"], legal)
        agent.table.pop(key, None)
        percept = self.module.Percept(current_direction=DIRECTIONS["UP"], legal_actions=legal)
        action = agent.choose_action(percept)
        self.assertIn(action, legal)


if __name__ == "__main__":
    unittest.main()
