"""Part 6 - Learning agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part6_learning -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402

from _helpers import TEST_LEVEL, load_module  # noqa: E402

AGENT_FILE = "learning_agent.py"


class TestPart6Learning(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # utility_based_agent.py must load first, under its natural module
        # name, so learning_agent.py's own `from utility_based_agent
        # import ...` picks up the SAME classes these tests use below.
        cls.utility_module = load_module("utility_based_agent.py")
        cls.module = load_module(AGENT_FILE)
        cls.maze = MazeModel(TEST_LEVEL)

    def new_agent(self, weights=None, seed=0):
        return self.module.LearningAgent(self.maze, weights=weights, seed=seed)

    def test_percept_class_matches_part_5(self):
        agent = self.new_agent()
        self.assertIs(agent.percept_class, self.utility_module.Percept)

    def test_choose_action_delegates_and_stays_legal(self):
        agent = self.new_agent()
        percept = agent.percept_class(
            player=(2, 2),
            current_direction=DIRECTIONS["RIGHT"],
            pellets=frozenset({(2, 3)}),
            power_pellets=frozenset(),
            released_ghosts=tuple(),
            legal_actions=(DIRECTIONS["LEFT"], DIRECTIONS["RIGHT"]),
            frightened_time_remaining=0.0,
        )
        action = agent.choose_action(percept)
        self.assertIn(action, percept.legal_actions)

    def test_propose_new_weights_changes_a_bounded_number_of_fields(self):
        agent = self.new_agent(seed=7)
        base = agent.best_weights
        proposal = agent.propose_new_weights()

        self.assertIsInstance(proposal, self.utility_module.UtilityWeights)
        changed = [
            name
            for name in base.__dataclass_fields__
            if getattr(proposal, name) != getattr(base, name)
        ]
        self.assertTrue(
            1 <= len(changed) <= 3,
            f"Part 6: propose_new_weights changed {len(changed)} fields "
            f"({changed}). This should be a SMALL nudge to one or two "
            "weights, not a full re-randomization.",
        )
        for name in changed:
            old, new = getattr(base, name), getattr(proposal, name)
            bound = 2.0 * max(abs(old), 1.0)
            self.assertLessEqual(
                abs(new - old),
                bound,
                f"Part 6: the nudge to {name} ({old} -> {new}) is too large "
                "to be a 'small perturbation'.",
            )

    def test_propose_new_weights_does_not_mutate_state(self):
        agent = self.new_agent(seed=3)
        before = agent.best_weights
        before_performance = agent.best_performance
        agent.propose_new_weights()
        self.assertEqual(agent.best_weights, before)
        self.assertEqual(agent.best_performance, before_performance)

    def test_learn_keeps_an_improvement(self):
        agent = self.new_agent()
        candidate = agent.propose_new_weights()
        agent.performance_element.weights = candidate
        agent.learn(1_000_000.0)
        self.assertEqual(agent.best_weights, candidate)
        self.assertEqual(agent.best_performance, 1_000_000.0)
        self.assertEqual(agent.weights, candidate)

    def test_learn_reverts_a_regression(self):
        agent = self.new_agent()
        agent.learn(500.0)  # establish a first "best"
        good_weights = agent.best_weights

        candidate = agent.propose_new_weights()
        agent.performance_element.weights = candidate
        agent.learn(-9999.0)

        self.assertEqual(agent.best_weights, good_weights)
        self.assertEqual(agent.weights, good_weights)

    def test_learn_counts_episodes(self):
        agent = self.new_agent()
        self.assertEqual(agent.episodes_seen, 0)
        agent.learn(1.0)
        agent.learn(2.0)
        self.assertEqual(agent.episodes_seen, 2)


if __name__ == "__main__":
    unittest.main()
