"""Behaviour tests: do the finished agents actually play better?

PROVIDED INFRASTRUCTURE. Do not edit this file.

The other test files check that each part is BUILT the right way. These
play full episodes on the real maze and check that the resulting BEHAVIOUR
matches what each agent type is supposed to buy you. They take longer to
run (a few seconds) because of that.

Run with:
    python -m unittest tests.test_trials_performance -v
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.headless import run_trials, summarize  # noqa: E402
from pacman.registry import resolve_agents  # noqa: E402

from _helpers import PROJECT_ROOT  # noqa: E402

SEEDS = list(range(1, 31))


class TestTrialsPerformance(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.agents = resolve_agents(
            ["utility_based", "model_based", "simple_reflex", "goal_based", "greedy"],
            PROJECT_ROOT,
        )
        cls.rows = run_trials(cls.agents, SEEDS, difficulty="normal")
        cls.summary = {row["agent"]: row for row in summarize(cls.rows)}

    def test_utility_based_finishes_every_episode_without_error(self):
        rows = [r for r in self.rows if r["agent"] == "utility_based"]
        self.assertEqual(len(rows), len(SEEDS))

    def test_utility_based_wins_most_episodes(self):
        win_rate = self.summary["utility_based"]["win_rate"]
        self.assertGreaterEqual(
            win_rate,
            0.60,
            f"Your utility-based agent (Part 5) cleared the maze in "
            f"{win_rate:.0%} of episodes on 'normal'. A finished one should "
            "win most of them. Check your ghost weights and food-distance "
            "term.",
        )

    def test_utility_based_beats_the_blind_greedy_baseline(self):
        """Part 5 is supposed to be worth the extra machinery: a ghost-aware
        utility function should clearly outperform an agent that is blind
        to ghosts entirely."""
        utility = self.summary["utility_based"]["mean_performance"]
        greedy = self.summary["greedy"]["mean_performance"]
        self.assertGreater(
            utility,
            greedy,
            f"Mean performance {utility} did not beat the ghost-blind "
            f"greedy baseline at {greedy}. Ghost-awareness should be "
            "worth something.",
        )

    def test_model_based_has_fewer_backtracks_than_simple_reflex(self):
        """This is the concrete, measurable version of the pacing failure
        Part 2 has and Part 3 fixes."""
        model_based = self.summary["model_based"]["mean_backtracks"]
        simple_reflex = self.summary["simple_reflex"]["mean_backtracks"]
        self.assertLessEqual(
            model_based,
            simple_reflex,
            f"Part 3 reversed into its previous tile {model_based} times "
            f"per episode on average, versus {simple_reflex} for the "
            "memoryless Part 2 agent. Memory should reduce that.",
        )

    def test_goal_based_beats_the_blind_greedy_baseline(self):
        goal_based = self.summary["goal_based"]["mean_performance"]
        greedy = self.summary["greedy"]["mean_performance"]
        self.assertGreater(
            goal_based,
            greedy,
            f"Mean performance {goal_based} did not beat the ghost-blind "
            f"greedy baseline at {greedy}.",
        )


if __name__ == "__main__":
    unittest.main()
