"""Part 2 - Simple reflex agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part2_simple_reflex -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

from _helpers import TEST_LEVEL, load_module  # noqa: E402

AGENT_FILE = "simple_reflex_agent.py"

REQUIRED_FIELDS = {
    "player",
    "current_direction",
    "pellets",
    "power_pellets",
    "released_ghosts",
    "legal_actions",
    "frightened_time_remaining",
}


class TestPart2SimpleReflex(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_module(AGENT_FILE)
        cls.maze = MazeModel(TEST_LEVEL)

    def new_agent(self):
        return self.module.SimpleReflexAgent(self.maze)

    def make_percept(self, **overrides):
        defaults = {
            "player": (2, 2),
            "current_direction": DIRECTIONS["RIGHT"],
            "pellets": frozenset({(2, 3), (1, 1)}),
            "power_pellets": frozenset(),
            "released_ghosts": tuple(),
            "legal_actions": tuple(DIRECTIONS.values()),
            "frightened_time_remaining": 0.0,
        }
        defaults.update(overrides)
        declared = [f.name for f in dataclasses.fields(self.module.Percept)]
        return self.module.Percept(**{name: defaults[name] for name in declared})

    def test_percept_declares_every_required_field(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        missing = REQUIRED_FIELDS - declared
        self.assertFalse(missing, f"Part 2: Percept is missing {sorted(missing)}.")

    def test_percept_fields_are_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(unknown, f"Part 2: unknown percept field(s) {unknown}")

    def test_agent_has_no_internal_state(self):
        """This is what separates a simple reflex agent from Part 3. If you
        find yourself wanting to add memory here, that need is exactly
        what motivates the next part -- it does not belong in this one."""
        agent = self.new_agent()
        self.assertFalse(
            hasattr(agent, "visit_counts") or hasattr(agent, "position_history"),
            "Part 2: a simple reflex agent has no memory of past percepts.",
        )

    def test_avoids_a_dangerous_adjacent_ghost_when_a_safe_option_exists(self):
        agent = self.new_agent()
        percept = self.make_percept(
            player=(2, 2),
            released_ghosts=((2, 3),),
            pellets=frozenset({(2, 3)}),
            legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["LEFT"]),
        )
        self.assertEqual(agent.choose_action(percept), DIRECTIONS["LEFT"])

    def test_eats_an_adjacent_frightened_ghost(self):
        agent = self.new_agent()
        percept = self.make_percept(
            player=(2, 2),
            released_ghosts=((2, 3),),
            frightened_time_remaining=5.0,
            legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["LEFT"]),
        )
        self.assertEqual(agent.choose_action(percept), DIRECTIONS["RIGHT"])

    def test_takes_an_adjacent_pellet_over_wandering(self):
        agent = self.new_agent()
        percept = self.make_percept(
            player=(2, 2),
            pellets=frozenset({(2, 3)}),
            current_direction=DIRECTIONS["UP"],
            legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["UP"]),
        )
        self.assertEqual(agent.choose_action(percept), DIRECTIONS["RIGHT"])

    def test_choose_action_never_returns_an_illegal_action(self):
        agent = self.new_agent()
        for legal in [
            (DIRECTIONS["LEFT"],),
            (DIRECTIONS["UP"], DIRECTIONS["DOWN"]),
            tuple(DIRECTIONS.values()),
        ]:
            percept = self.make_percept(legal_actions=legal)
            self.assertIn(agent.choose_action(percept), legal)

    def test_no_legal_actions_is_handled(self):
        agent = self.new_agent()
        percept = self.make_percept(legal_actions=tuple())
        self.assertEqual(agent.choose_action(percept), (0, 0))
        self.assertIn("No legal", agent.last_reason)


if __name__ == "__main__":
    unittest.main()
