"""Part 4 - Goal-based agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part4_goal_based -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

from _helpers import load_module  # noqa: E402

AGENT_FILE = "goal_based_agent.py"

REQUIRED_FIELDS = {
    "player",
    "pellets",
    "power_pellets",
    "released_ghosts",
    "legal_actions",
    "frightened_time_remaining",
}

# A longer corridor, so "close to a ghost" and "far from a ghost" are
# meaningfully different tiles.
CORRIDOR_LEVEL = (
    "###########",
    "#P........#",
    "###########",
)


class TestPart4GoalBased(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_module(AGENT_FILE)
        cls.maze = MazeModel(CORRIDOR_LEVEL)

    def new_agent(self):
        return self.module.GoalBasedAgent(self.maze)

    def make_percept(self, agent, **overrides):
        defaults = {
            "player": (1, 1),
            "pellets": frozenset({(1, 9)}),
            "power_pellets": frozenset(),
            "released_ghosts": tuple(),
            "legal_actions": (DIRECTIONS["LEFT"], DIRECTIONS["RIGHT"]),
            "frightened_time_remaining": 0.0,
        }
        defaults.update(overrides)
        declared = [f.name for f in dataclasses.fields(agent.percept_class)]
        return agent.percept_class(**{name: defaults[name] for name in declared})

    def test_percept_declares_every_required_field(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        missing = REQUIRED_FIELDS - declared
        self.assertFalse(missing, f"Part 4: Percept is missing {sorted(missing)}.")

    def test_percept_fields_are_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(unknown, f"Part 4: unknown percept field(s) {unknown}")

    def test_determine_goal_seeks_food_when_no_danger(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, player=(1, 1), pellets=frozenset({(1, 9)}))
        kind, positions = agent.determine_goal(percept)
        self.assertEqual(kind, "seek")
        self.assertIn((1, 9), positions)

    def test_determine_goal_flees_a_close_dangerous_ghost(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent,
            player=(1, 5),
            released_ghosts=((1, 6),),
            frightened_time_remaining=0.0,
        )
        kind, positions = agent.determine_goal(percept)
        self.assertEqual(kind, "flee")
        self.assertIn((1, 6), positions)

    def test_determine_goal_ignores_a_frightened_ghost_as_a_threat(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent,
            player=(1, 5),
            released_ghosts=((1, 6),),
            frightened_time_remaining=5.0,
        )
        kind, _ = agent.determine_goal(percept)
        self.assertEqual(kind, "seek")

    def test_goal_test_reports_seek_goal_achieved_on_the_goal_tile(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, pellets=frozenset({(1, 9)}))
        goal = agent.determine_goal(percept)
        self.assertTrue(agent.goal_test((1, 9), goal))
        self.assertFalse(agent.goal_test((1, 1), goal))

    def test_moves_toward_food_when_safe(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent, player=(1, 5), pellets=frozenset({(1, 9)}), released_ghosts=()
        )
        self.assertEqual(agent.choose_action(percept), DIRECTIONS["RIGHT"])

    def test_moves_away_from_a_close_dangerous_ghost(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent,
            player=(1, 5),
            pellets=frozenset({(1, 9)}),
            released_ghosts=((1, 6),),
        )
        self.assertEqual(agent.choose_action(percept), DIRECTIONS["LEFT"])

    def test_choose_action_never_returns_an_illegal_action(self):
        agent = self.new_agent()
        for legal in [(DIRECTIONS["LEFT"],), (DIRECTIONS["RIGHT"],)]:
            percept = self.make_percept(agent, legal_actions=legal)
            self.assertIn(agent.choose_action(percept), legal)

    def test_no_legal_actions_is_handled(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, legal_actions=tuple())
        self.assertEqual(agent.choose_action(percept), (0, 0))
        self.assertIn("No legal", agent.last_reason)


if __name__ == "__main__":
    unittest.main()
