"""Part 5 - Utility-based agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part5_utility_based -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

from _helpers import TEST_LEVEL, load_module  # noqa: E402

AGENT_FILE = "utility_based_agent.py"

REQUIRED_FIELDS = {
    "player",
    "current_direction",
    "pellets",
    "power_pellets",
    "released_ghosts",
    "legal_actions",
    "frightened_time_remaining",
}

REQUIRED_CONTRIBUTION_KEYS = (
    "food_distance",
    "regular_pellet",
    "power_pellet",
    "ghost",
    "continuation",
    "revisit",
    "backtrack",
    "food_distance_steps",
    "ghost_distance_steps",
    "revisit_count",
)

WEIGHTED_KEYS = (
    "food_distance",
    "regular_pellet",
    "power_pellet",
    "ghost",
    "continuation",
    "revisit",
    "backtrack",
)


class TestPart5UtilityBased(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_module(AGENT_FILE)
        cls.maze = MazeModel(TEST_LEVEL)

    def new_agent(self):
        return self.module.UtilityBasedAgent(self.maze)

    def make_percept(self, agent, **overrides):
        defaults = {
            "player": (2, 2),
            "current_direction": DIRECTIONS["RIGHT"],
            "pellets": frozenset({(2, 3), (1, 1)}),
            "power_pellets": frozenset(),
            "released_ghosts": tuple(),
            "legal_actions": tuple(DIRECTIONS.values()),
            "frightened_time_remaining": 0.0,
        }
        defaults.update(overrides)
        declared = [f.name for f in dataclasses.fields(agent.percept_class)]
        return agent.percept_class(**{name: defaults[name] for name in declared})

    # -- percept ---------------------------------------------------------

    def test_percept_declares_every_required_field(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        missing = REQUIRED_FIELDS - declared
        self.assertFalse(missing, f"Part 5: Percept is missing {sorted(missing)}.")

    def test_percept_fields_are_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(unknown, f"Part 5: unknown percept field(s) {unknown}")

    # -- named weights -----------------------------------------------

    def test_weights_cover_ghosts_revisit_and_backtrack(self):
        names = {f.name for f in dataclasses.fields(self.module.UtilityWeights)}
        self.assertGreaterEqual(len(names), 10)
        joined = " ".join(names).lower()
        for topic in ("ghost", "revisit", "backtrack"):
            self.assertIn(topic, joined)

    def test_weights_are_actually_used(self):
        """Flipping the collision weight must change what the agent does."""
        ghost_tile = (2, 3)
        right = DIRECTIONS["RIGHT"]

        cautious = self.new_agent()
        percept = self.make_percept(
            cautious, released_ghosts=(ghost_tile,), pellets=frozenset({(2, 3)})
        )
        self.assertNotEqual(cautious.choose_action(percept), right)

        reckless = self.new_agent()
        collision_field = next(
            (
                f.name
                for f in dataclasses.fields(self.module.UtilityWeights)
                if "collision" in f.name or "caught" in f.name
            ),
            None,
        )
        self.assertIsNotNone(collision_field)
        reckless.weights = dataclasses.replace(
            reckless.weights, **{collision_field: 5000.0}
        )
        reckless_percept = self.make_percept(
            reckless, released_ghosts=(ghost_tile,), pellets=frozenset({(2, 3)})
        )
        self.assertEqual(reckless.choose_action(reckless_percept), right)

    # -- evaluate_action ---------------------------------------------

    def test_returns_utility_and_named_contributions(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        result = agent.evaluate_action(percept, DIRECTIONS["RIGHT"])
        self.assertIsInstance(result, tuple)
        self.assertEqual(len(result), 2)
        utility, contributions = result
        self.assertIsInstance(utility, float)
        self.assertIsInstance(contributions, dict)
        missing = [k for k in REQUIRED_CONTRIBUTION_KEYS if k not in contributions]
        self.assertFalse(missing)

    def test_weighted_terms_sum_to_the_total(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        utility, contributions = agent.evaluate_action(percept, DIRECTIONS["RIGHT"])
        self.assertAlmostEqual(
            utility, sum(contributions[k] for k in WEIGHTED_KEYS), places=6
        )

    def test_illegal_action_raises(self):
        agent = self.new_agent()
        percept = self.make_percept(
            agent, legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["LEFT"])
        )
        with self.assertRaises(ValueError):
            agent.evaluate_action(percept, DIRECTIONS["UP"])

    def test_nearby_ghost_lowers_utility(self):
        agent = self.new_agent()
        right = DIRECTIONS["RIGHT"]
        safe, _ = agent.evaluate_action(self.make_percept(agent), right)
        risky, _ = agent.evaluate_action(
            self.make_percept(agent, released_ghosts=((2, 3),)), right
        )
        self.assertLess(risky, safe)

    def test_frightened_ghost_raises_utility(self):
        agent = self.new_agent()
        right = DIRECTIONS["RIGHT"]
        dangerous, _ = agent.evaluate_action(
            self.make_percept(agent, released_ghosts=((2, 3),)), right
        )
        edible, _ = agent.evaluate_action(
            self.make_percept(
                agent, released_ghosts=((2, 3),), frightened_time_remaining=5.0
            ),
            right,
        )
        self.assertGreater(edible, dangerous)

    def test_memory_lowers_the_utility_of_a_stale_tile(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        right = DIRECTIONS["RIGHT"]

        fresh_utility, fresh = agent.evaluate_action(percept, right)
        agent.visit_counts[(2, 3)] = 5
        stale_utility, stale = agent.evaluate_action(percept, right)

        self.assertLess(stale_utility, fresh_utility)
        self.assertLess(stale["revisit"], fresh["revisit"])

    # -- selection -----------------------------------------------------

    def test_no_legal_action_is_handled(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, legal_actions=tuple())
        self.assertEqual(agent.choose_action(percept), (0, 0))
        self.assertIn("No legal", agent.last_reason)

    def test_returned_action_is_always_legal(self):
        agent = self.new_agent()
        for legal in [
            (DIRECTIONS["LEFT"],),
            (DIRECTIONS["UP"], DIRECTIONS["DOWN"]),
            tuple(DIRECTIONS.values()),
        ]:
            percept = self.make_percept(agent, legal_actions=legal)
            self.assertIn(agent.choose_action(percept), legal)

    def test_choose_action_updates_memory_once_per_turn(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        agent.choose_action(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 1)
        agent.choose_action(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 2)

    def test_selection_uses_evaluate_action(self):
        agent = self.new_agent()
        target = DIRECTIONS["DOWN"]

        def fake_evaluate(percept, action):
            score = 100.0 if action == target else -100.0
            return score, {key: 0.0 for key in REQUIRED_CONTRIBUTION_KEYS}

        agent.evaluate_action = fake_evaluate
        self.assertEqual(agent.choose_action(self.make_percept(agent)), target)

    def test_last_reason_reports_the_evidence(self):
        agent = self.new_agent()
        agent.choose_action(self.make_percept(agent))
        for token in ("U=", "food=", "ghost=", "memory="):
            self.assertIn(token, agent.last_reason)
        self.assertLessEqual(len(agent.last_reason), 120)


if __name__ == "__main__":
    unittest.main()
