"""Part 3 - Model-based reflex agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Run with:
    python -m unittest tests.test_part3_model_based -v
"""

from __future__ import annotations

import dataclasses
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pacman.maze import DIRECTIONS, MazeModel  # noqa: E402
from pacman.rules import Simulation  # noqa: E402

from _helpers import TEST_LEVEL, load_module  # noqa: E402

AGENT_FILE = "model_based_agent.py"

REQUIRED_FIELDS = {
    "player",
    "current_direction",
    "pellets",
    "power_pellets",
    "released_ghosts",
    "legal_actions",
    "frightened_time_remaining",
}


class TestPart3ModelBased(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.module = load_module(AGENT_FILE)
        cls.maze = MazeModel(TEST_LEVEL)

    def new_agent(self):
        return self.module.ModelBasedAgent(self.maze)

    def make_percept(self, agent, **overrides):
        defaults = {
            "player": (2, 2),
            "current_direction": DIRECTIONS["RIGHT"],
            "pellets": frozenset(),
            "power_pellets": frozenset(),
            "released_ghosts": tuple(),
            "legal_actions": tuple(DIRECTIONS.values()),
            "frightened_time_remaining": 0.0,
        }
        defaults.update(overrides)
        declared = [f.name for f in dataclasses.fields(agent.percept_class)]
        return agent.percept_class(**{name: defaults[name] for name in declared})

    def test_percept_declares_every_required_field(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        missing = REQUIRED_FIELDS - declared
        self.assertFalse(missing, f"Part 3: Percept is missing {sorted(missing)}.")

    def test_percept_fields_are_sensable(self):
        declared = {f.name for f in dataclasses.fields(self.module.Percept)}
        unknown = declared - set(Simulation.SENSOR_FIELDS)
        self.assertFalse(unknown, f"Part 3: unknown percept field(s) {unknown}")

    def test_internal_state_exists(self):
        agent = self.new_agent()
        self.assertTrue(hasattr(agent, "visit_counts"))
        self.assertTrue(hasattr(agent, "position_history"))

    def test_update_internal_state_records_the_percept(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        agent.update_internal_state(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 1)
        agent.update_internal_state(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 2)
        self.assertIn((2, 2), list(agent.position_history))

    def test_position_history_is_bounded(self):
        agent = self.new_agent()
        for _ in range(50):
            agent.update_internal_state(self.make_percept(agent))
        self.assertLessEqual(
            len(agent.position_history),
            8,
            "Part 3: position_history should be a short rolling window "
            "(collections.deque(maxlen=4)), not an unbounded log.",
        )

    def test_choose_action_updates_memory_exactly_once_per_turn(self):
        agent = self.new_agent()
        percept = self.make_percept(agent)
        agent.choose_action(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 1)
        agent.choose_action(percept)
        self.assertEqual(agent.visit_counts.get((2, 2)), 2)

    def test_prefers_the_least_visited_safe_tile(self):
        """With no pellets, no ghosts, and no forced backtrack, memory is
        the only thing left to decide with -- so the least-visited option
        must win."""
        agent = self.new_agent()
        percept = self.make_percept(
            agent,
            player=(2, 2),
            legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["LEFT"]),
        )
        agent.visit_counts[(2, 3)] = 5  # RIGHT lands here
        agent.visit_counts[(2, 1)] = 0  # LEFT lands here
        agent.position_history.extend([(1, 1), (1, 2)])
        action = agent.choose_action(percept)
        self.assertEqual(action, DIRECTIONS["LEFT"])

    def test_avoids_backtracking_when_a_non_backtrack_option_exists(self):
        agent = self.new_agent()
        # Turn 1: at (2,2), moving right.
        agent.choose_action(
            self.make_percept(
                agent,
                player=(2, 2),
                legal_actions=(DIRECTIONS["RIGHT"], DIRECTIONS["UP"]),
            )
        )
        # Turn 2: at (2,3). LEFT goes straight back to (2,2) (two turns
        # ago once this turn is recorded); UP does not.
        action = agent.choose_action(
            self.make_percept(
                agent,
                player=(2, 3),
                legal_actions=(DIRECTIONS["LEFT"], DIRECTIONS["UP"]),
            )
        )
        self.assertEqual(action, DIRECTIONS["UP"])

    def test_choose_action_never_returns_an_illegal_action(self):
        agent = self.new_agent()
        for legal in [
            (DIRECTIONS["LEFT"],),
            (DIRECTIONS["UP"], DIRECTIONS["DOWN"]),
            tuple(DIRECTIONS.values()),
        ]:
            percept = self.make_percept(agent, legal_actions=legal)
            self.assertIn(agent.choose_action(percept), legal)

    def test_no_legal_actions_is_handled(self):
        agent = self.new_agent()
        percept = self.make_percept(agent, legal_actions=tuple())
        self.assertEqual(agent.choose_action(percept), (0, 0))
        self.assertIn("No legal", agent.last_reason)


if __name__ == "__main__":
    unittest.main()
