"""Moving pieces on the board.

PROVIDED INFRASTRUCTURE. Do not edit this file.

These objects are part of the *environment*, not the agent. The agent never
receives one; it only ever sees the coordinates that appear in its percept.
"""

from __future__ import annotations

from .maze import DIRECTIONS


class Entity:
    """A thing that occupies one maze tile and remembers where it just was.

    ``prev_row`` / ``prev_col`` exist purely so the renderer can draw smooth
    motion between two grid tiles. All game rules use whole-tile positions.
    """

    def __init__(self, row: int, col: int, color: tuple[int, int, int]):
        self.row = row
        self.col = col
        self.prev_row = row
        self.prev_col = col
        self.color = color
        self.direction: tuple[int, int] = (0, 0)

    @property
    def position(self) -> tuple[int, int]:
        return self.row, self.col

    @property
    def previous_position(self) -> tuple[int, int]:
        return self.prev_row, self.prev_col


class PacMan(Entity):
    def __init__(self, row: int, col: int, color: tuple[int, int, int]):
        super().__init__(row, col, color)


class Ghost(Entity):
    def __init__(
        self,
        row: int,
        col: int,
        color: tuple[int, int, int],
        release_delay_ms: int,
    ):
        super().__init__(row, col, color)
        self.spawn = (row, col)
        self.release_delay_ms = release_delay_ms
        self.released = False
        self.direction = DIRECTIONS["UP"]
