"""Headless trials.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Runs episodes with no window so you can compare agents fairly. Every agent
in a comparison sees the SAME list of seeds, and a seed fully determines
ghost behaviour, so a difference in results is a difference in the agents
rather than a difference in luck.
"""

from __future__ import annotations

import csv
import statistics
from pathlib import Path
from typing import Any, Callable, Iterable, Sequence

from .maze import MazeModel
from .rules import DIFFICULTIES, Difficulty, Simulation

AgentFactory = Callable[[MazeModel], Any]

TRIAL_COLUMNS = (
    "agent",
    "difficulty",
    "seed",
    "outcome",
    "score",
    "decisions",
    "elapsed_seconds",
    "pellets_left",
    "ghosts_eaten",
    "repeat_visits",
    "immediate_backtracks",
    "performance",
)

SUMMARY_COLUMNS = (
    "agent",
    "difficulty",
    "trials",
    "win_rate",
    "caught_rate",
    "mean_score",
    "mean_decisions",
    "mean_backtracks",
    "mean_performance",
    "stdev_performance",
)


def run_episode(
    agent_factory: AgentFactory,
    seed: int,
    maze: MazeModel,
    difficulty: Difficulty,
    max_decisions: int = 1500,
    max_time_ms: int = 240_000,
) -> dict[str, Any]:
    agent = agent_factory(maze)
    sim = Simulation(
        maze,
        agent,
        seed=seed,
        ghost_period_ms=difficulty.ghost_period_ms,
        chase_probability=difficulty.chase_probability,
    )

    while (
        not sim.game_over
        and sim.decisions < max_decisions
        and sim.time_ms < max_time_ms
    ):
        sim.advance_one_tick()

    return {"difficulty": difficulty.name, **sim.report()}


def run_trials(
    agents: dict[str, AgentFactory],
    seeds: Sequence[int],
    difficulty: Difficulty | str = "normal",
    max_decisions: int = 1500,
    max_time_ms: int = 240_000,
) -> list[dict[str, Any]]:
    if isinstance(difficulty, str):
        difficulty = DIFFICULTIES[difficulty]

    maze = MazeModel(difficulty.level)
    rows: list[dict[str, Any]] = []

    for seed in seeds:
        for name, factory in agents.items():
            report = run_episode(
                factory, seed, maze, difficulty, max_decisions, max_time_ms
            )
            rows.append({"agent": name, **report})

    return rows


def summarize(rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = list(rows)
    summaries: list[dict[str, Any]] = []
    keys = dict.fromkeys((row["agent"], row.get("difficulty", "")) for row in rows)

    for name, difficulty in keys:
        group = [
            row
            for row in rows
            if row["agent"] == name and row.get("difficulty", "") == difficulty
        ]
        performances = [row["performance"] for row in group]
        summaries.append(
            {
                "agent": name,
                "difficulty": difficulty,
                "trials": len(group),
                "win_rate": round(
                    sum(row["outcome"] == "win" for row in group) / len(group), 3
                ),
                "caught_rate": round(
                    sum(row["outcome"] == "caught" for row in group) / len(group), 3
                ),
                "mean_score": round(statistics.fmean(r["score"] for r in group), 2),
                "mean_decisions": round(
                    statistics.fmean(r["decisions"] for r in group), 2
                ),
                "mean_backtracks": round(
                    statistics.fmean(r["immediate_backtracks"] for r in group), 2
                ),
                "mean_performance": round(statistics.fmean(performances), 2),
                "stdev_performance": round(
                    statistics.stdev(performances) if len(performances) > 1 else 0.0, 2
                ),
            }
        )

    return summaries


def write_csv(
    path: Path, rows: Sequence[dict[str, Any]], columns: Sequence[str]
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(columns))
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in columns})


def format_summary_table(summaries: Sequence[dict[str, Any]]) -> str:
    headers = [
        ("agent", 15),
        ("difficulty", 11),
        ("trials", 7),
        ("win_rate", 9),
        ("caught_rate", 12),
        ("mean_score", 11),
        ("mean_decisions", 15),
        ("mean_performance", 17),
    ]
    lines = ["  ".join(name.ljust(width) for name, width in headers)]
    lines.append("  ".join("-" * width for _, width in headers))
    for row in summaries:
        lines.append("  ".join(str(row[name]).ljust(width) for name, width in headers))
    return "\n".join(lines)
