"""Static maze knowledge.

PROVIDED INFRASTRUCTURE. Do not edit this file.

This module holds everything about the maze that never changes while the
game is running: wall layout, corridor connectivity, and the distance
between two locations. In AIMA terms this is the agent's *prior knowledge*
of a known environment (AIMA 4e Section 2.3.1, "known vs. unknown").

Anything that changes during play -- where Pac-Man is, where the ghosts
are, which pellets are left, whether frightened mode is active -- is NOT
here. That information reaches the agent only through its percept.
"""

from __future__ import annotations

from collections import deque
from typing import Iterable, Iterator

# Actions are (dx, dy) column/row offsets.
DIRECTIONS: dict[str, tuple[int, int]] = {
    "LEFT": (-1, 0),
    "RIGHT": (1, 0),
    "UP": (0, -1),
    "DOWN": (0, 1),
}

# Fixed iteration order. Keeping this stable makes tie-breaking
# deterministic, which matters when you compare trial runs.
DIRECTION_ORDER: tuple[tuple[int, int], ...] = tuple(DIRECTIONS.values())

DIRECTION_NAMES: dict[tuple[int, int], str] = {
    action: name for name, action in DIRECTIONS.items()
}

UNREACHABLE = 10_000

# Maze legend:
#   #      wall
#   .      regular pellet
#   o      power pellet
#   P      Pac-Man start
#   1-4    ghost start (inside the ghost house)
#   =      ghost-house door
#   space  open corridor, no pellet
LEVEL: tuple[str, ...] = (
    "#################",
    "#......###......#",
    "#.###o.......o#.#",
    "#.....###.###...#",
    "###.#.......#.###",
    "#...# #===###...#",
    "#o#.# #231#.#.#o#",
    "#...# #####.#...#",
    "#.......P.......#",
    "#################",
)


class MazeModel:
    """Read-only description of the maze.

    The agent is given one of these at construction time. It exposes only
    static facts. There is deliberately no way to reach ghost positions,
    the score, or frightened mode from here.
    """

    def __init__(self, level: Iterable[str] = LEVEL):
        rows = list(level)
        self.rows: int = len(rows)
        self.cols: int = max(len(row) for row in rows)

        self._grid: list[list[str]] = []
        self.player_start: tuple[int, int] = (0, 0)
        self.pellet_start: frozenset[tuple[int, int]] = frozenset()
        self.power_pellet_start: frozenset[tuple[int, int]] = frozenset()
        self.ghost_starts: tuple[tuple[int, tuple[int, int]], ...] = ()
        self.door_tiles: frozenset[tuple[int, int]] = frozenset()

        pellets: set[tuple[int, int]] = set()
        power_pellets: set[tuple[int, int]] = set()
        ghosts: list[tuple[int, tuple[int, int]]] = []
        doors: set[tuple[int, int]] = set()

        for row_index, raw_row in enumerate(rows):
            padded = raw_row.ljust(self.cols)
            grid_row: list[str] = []

            for col_index, cell in enumerate(padded):
                if cell == "#":
                    grid_row.append("#")
                elif cell == "=":
                    grid_row.append("=")
                    doors.add((row_index, col_index))
                else:
                    grid_row.append(" ")

                if cell == ".":
                    pellets.add((row_index, col_index))
                elif cell == "o":
                    power_pellets.add((row_index, col_index))
                elif cell == "P":
                    self.player_start = (row_index, col_index)
                elif cell in "1234":
                    ghosts.append((int(cell) - 1, (row_index, col_index)))
                elif cell not in "# =":
                    raise ValueError(
                        f"Unknown maze character {cell!r} at row {row_index}, "
                        f"column {col_index}. See the legend in pacman/maze.py."
                    )

            self._grid.append(grid_row)

        self.pellet_start = frozenset(pellets)
        self.power_pellet_start = frozenset(power_pellets)
        self.ghost_starts = tuple(sorted(ghosts))
        self.door_tiles = frozenset(doors)

    # -- basic geometry ------------------------------------------------

    def wrap_col(self, col: int) -> int:
        """Columns wrap around, so the maze is a horizontal cylinder."""
        return col % self.cols

    def is_wall(self, row: int, col: int) -> bool:
        if row < 0 or row >= self.rows:
            return True
        if col < 0 or col >= self.cols:
            return False
        return self._grid[row][col] == "#"

    def is_ghost_door(self, row: int, col: int) -> bool:
        if row < 0 or row >= self.rows or col < 0 or col >= self.cols:
            return False
        return self._grid[row][col] == "="

    def cell(self, row: int, col: int) -> str:
        if row < 0 or row >= self.rows:
            return "#"
        return self._grid[row][self.wrap_col(col)]

    def step(self, position: tuple[int, int], action: tuple[int, int]) -> tuple[int, int]:
        """Where you land if you take ``action`` from ``position``."""
        row, col = position
        dx, dy = action
        return row + dy, self.wrap_col(col + dx)

    # -- connectivity --------------------------------------------------

    def legal_actions_from(
        self,
        position: tuple[int, int],
        allow_house_door: bool = False,
    ) -> tuple[tuple[int, int], ...]:
        """Actions that do not walk into a wall."""
        actions = []
        for action in DIRECTION_ORDER:
            next_row, next_col = self.step(position, action)
            if self.is_wall(next_row, next_col):
                continue
            if self.is_ghost_door(next_row, next_col) and not allow_house_door:
                continue
            actions.append(action)
        return tuple(actions)

    def neighbors(
        self,
        position: tuple[int, int],
        allow_house_door: bool = False,
    ) -> Iterator[tuple[tuple[int, int], tuple[int, int]]]:
        """Yield ``(next_position, action)`` pairs reachable in one step."""
        for action in self.legal_actions_from(position, allow_house_door):
            yield self.step(position, action), action

    # -- provided distance oracle --------------------------------------

    def distance(
        self,
        start: tuple[int, int],
        goals: Iterable[tuple[int, int]],
    ) -> int:
        """Steps from ``start`` to the nearest tile in ``goals``.

        This is PROVIDED for you. Chapter 2 is about agent structure, not
        about search algorithms, so treat this as a sensor-grade oracle:
        you may call it, and you are not asked to reimplement or improve
        it. Search algorithms are Chapter 3.

        Returns 0 if ``goals`` is empty or already contains ``start``, and
        ``UNREACHABLE`` if no goal can be reached.
        """
        goal_set = frozenset(goals)
        if not goal_set or start in goal_set:
            return 0

        queue: deque[tuple[tuple[int, int], int]] = deque([(start, 0)])
        visited = {start}

        while queue:
            position, distance = queue.popleft()
            for next_position, _ in self.neighbors(position):
                if next_position in visited:
                    continue
                if next_position in goal_set:
                    return distance + 1
                visited.add(next_position)
                queue.append((next_position, distance + 1))

        return UNREACHABLE
