"""Look up an agent by name.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Six of the names below load one of YOUR files from the project root. Two
more (``random``, ``greedy``) are external baselines provided for
comparison. Everything is resolved by name so ``tools/play.py`` and
``tools/run_trials.py`` can mix and match without caring which part of the
project a given agent came from.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, Callable

from .agents import GreedyBaselineAgent, RandomAgent
from .maze import MazeModel

AgentFactory = Callable[[MazeModel], Any]

BUILTIN_AGENTS: dict[str, AgentFactory] = {
    "random": lambda maze: RandomAgent(maze),
    "greedy": lambda maze: GreedyBaselineAgent(maze),
}

#: name -> (filename at the project root, class the file must define)
STUDENT_PARTS: dict[str, tuple[str, str]] = {
    "table_driven": ("table_driven_agent.py", "TableDrivenAgent"),
    "simple_reflex": ("simple_reflex_agent.py", "SimpleReflexAgent"),
    "model_based": ("model_based_agent.py", "ModelBasedAgent"),
    "goal_based": ("goal_based_agent.py", "GoalBasedAgent"),
    "utility_based": ("utility_based_agent.py", "UtilityBasedAgent"),
    "learning": ("learning_agent.py", "LearningAgent"),
}


def _load_module(path: Path, module_name: str):
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(f"No file at {path}")

    project_root = path.parent
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def load_student_agent(part: str, project_root: Path | str = ".") -> AgentFactory:
    """Import one of your six part files and return a factory for its agent."""
    if part not in STUDENT_PARTS:
        known = ", ".join(sorted(STUDENT_PARTS))
        raise ValueError(f"Unknown part {part!r}. Choose from: {known}")

    filename, class_name = STUDENT_PARTS[part]
    path = Path(project_root) / filename
    module = _load_module(path, f"student_{part}")

    if not hasattr(module, class_name):
        raise AttributeError(f"{path} does not define {class_name}")

    agent_class = getattr(module, class_name)
    return lambda maze: agent_class(maze)


def resolve_agents(
    names: list[str],
    project_root: Path | str = ".",
) -> dict[str, AgentFactory]:
    """Turn a list of agent names into name -> factory."""
    agents: dict[str, AgentFactory] = {}
    for name in names:
        key = name.strip()
        if not key:
            continue
        if key in BUILTIN_AGENTS:
            agents[key] = BUILTIN_AGENTS[key]
        elif key in STUDENT_PARTS:
            agents[key] = load_student_agent(key, project_root)
        else:
            known = ", ".join(sorted(set(BUILTIN_AGENTS) | set(STUDENT_PARTS)))
            raise ValueError(f"Unknown agent {key!r}. Choose from: {known}")
    return agents
