"""Interactive window.

PROVIDED INFRASTRUCTURE. Do not edit this file.

This is a view onto ``Simulation``. It contains no game rules of its own,
so what you see here is exactly what the headless trial runner scores.

The bottom bar prints your agent's ``last_reason`` every turn. That line is
the fastest way to debug a utility function: you can watch the percept turn
into a number and the number turn into a move.
"""

from __future__ import annotations

import math

import pygame

from .maze import MazeModel
from .rules import DIFFICULTIES, Difficulty, Simulation

TILE_SIZE = 30
HUD_HEIGHT = 76
FPS = 60

BLACK = (0, 0, 0)
MAZE_BLUE = (15, 35, 255)
WHITE = (245, 245, 245)
GREY = (150, 150, 150)
YELLOW = (255, 230, 0)
PINK = (255, 185, 220)
GREEN = (60, 220, 100)
RED = (245, 70, 55)
FRIGHTENED_BLUE = (45, 80, 230)


class Window:
    def __init__(
        self,
        agent_factory,
        agent_label: str,
        seed: int = 0,
        maze: MazeModel | None = None,
        difficulty: Difficulty | None = None,
    ):
        # display + font only: pygame.init() also opens the audio device,
        # which prints noisy warnings on machines with no sound card.
        pygame.display.init()
        pygame.font.init()
        pygame.display.set_caption(f"Pac-Man as an Autonomous Agent - {agent_label}")

        self.agent_factory = agent_factory
        self.agent_label = agent_label
        self.seed = seed
        self.difficulty = difficulty or DIFFICULTIES["normal"]
        self.maze = maze if maze is not None else MazeModel(self.difficulty.level)

        self.width = self.maze.cols * TILE_SIZE
        self.board_height = self.maze.rows * TILE_SIZE
        self.height = self.board_height + HUD_HEIGHT

        self.screen = pygame.display.set_mode((self.width, self.height))
        self.clock = pygame.time.Clock()
        self.font = pygame.font.SysFont("consolas", 22, bold=True)
        self.small_font = pygame.font.SysFont("consolas", 13)

        self.maze_bg = self._build_maze_surface()
        self.paused = False
        self.sim = self._new_simulation()

    def _new_simulation(self) -> Simulation:
        agent = self.agent_factory(self.maze)
        return Simulation(
            self.maze,
            agent,
            seed=self.seed,
            ghost_period_ms=self.difficulty.ghost_period_ms,
            chase_probability=self.difficulty.chase_probability,
        )

    # -- static maze art ------------------------------------------------

    def _build_maze_surface(self) -> pygame.Surface:
        """Render walls at 4x and downscale for clean anti-aliased edges."""
        scale = 4
        surface = pygame.Surface((self.width * scale, self.board_height * scale))
        surface.fill(BLACK)

        blue_width = 20 * scale
        black_width = 14 * scale
        tile = TILE_SIZE * scale

        for width, color in ((blue_width, MAZE_BLUE), (black_width, BLACK)):
            radius = width // 2
            for row in range(self.maze.rows):
                for col in range(self.maze.cols):
                    if not self.maze.is_wall(row, col):
                        continue
                    x = col * tile + tile // 2
                    y = row * tile + tile // 2
                    pygame.draw.circle(surface, color, (x, y), radius)
                    if col < self.maze.cols - 1 and self.maze.is_wall(row, col + 1):
                        pygame.draw.line(surface, color, (x, y), (x + tile, y), width)
                    if row < self.maze.rows - 1 and self.maze.is_wall(row + 1, col):
                        pygame.draw.line(surface, color, (x, y), (x, y + tile), width)

        for row, col in self.maze.door_tiles:
            y = row * tile + tile // 2
            x_start = col * tile + 3 * scale
            x_end = col * tile + tile - 3 * scale
            pygame.draw.line(surface, PINK, (x_start, y), (x_end, y), 4 * scale)

        return pygame.transform.smoothscale(
            surface, (self.width, self.board_height)
        )

    # -- entity art -----------------------------------------------------

    def _pixel_center(self, entity, progress: float) -> tuple[float, float]:
        start_col = entity.prev_col
        if abs(entity.col - entity.prev_col) > 1:
            start_col = entity.col - entity.direction[0]

        start_x = start_col * TILE_SIZE + TILE_SIZE // 2
        start_y = entity.prev_row * TILE_SIZE + TILE_SIZE // 2
        end_x = entity.col * TILE_SIZE + TILE_SIZE // 2
        end_y = entity.row * TILE_SIZE + TILE_SIZE // 2

        return (
            start_x + (end_x - start_x) * progress,
            start_y + (end_y - start_y) * progress,
        )

    def _draw_pacman(self, progress: float) -> None:
        player = self.sim.player
        x, y = self._pixel_center(player, progress)
        radius = TILE_SIZE // 2 - 3

        pygame.draw.circle(self.screen, player.color, (int(x), int(y)), radius)

        cycle = (pygame.time.get_ticks() % 300) / 150.0
        if cycle > 1.0:
            cycle = 2.0 - cycle
        mouth_angle = 2 + 43 * cycle

        facing = {
            (1, 0): 0,
            (-1, 0): 180,
            (0, -1): 90,
            (0, 1): 270,
        }.get(player.direction, 0)

        start_rad = math.radians(facing - mouth_angle)
        end_rad = math.radians(facing + mouth_angle)

        points = [(x, y)]
        for index in range(11):
            angle = start_rad + (end_rad - start_rad) * (index / 10.0)
            points.append(
                (
                    x + (radius + 2) * math.cos(angle),
                    y - (radius + 2) * math.sin(angle),
                )
            )
        pygame.draw.polygon(self.screen, BLACK, points)

    def _draw_ghost(self, ghost, progress: float, frightened: bool) -> None:
        x, y = self._pixel_center(ghost, progress)
        radius = TILE_SIZE // 2 - 3
        body = FRIGHTENED_BLUE if frightened else ghost.color

        pygame.draw.circle(self.screen, body, (x, y - 3), radius)
        pygame.draw.rect(self.screen, body, (x - radius, y - 3, radius * 2, radius + 6))

        for index in range(3):
            pygame.draw.circle(
                self.screen,
                BLACK,
                (x - radius + 5 + index * (radius - 2), y + radius + 1),
                4,
            )

        eye_y = y - 6
        dx, dy = ghost.direction
        pupil = WHITE if frightened else MAZE_BLUE
        for offset in (-6, 6):
            pygame.draw.circle(self.screen, WHITE, (x + offset, eye_y), 5)
            pygame.draw.circle(
                self.screen, pupil, (x + offset + dx * 2, eye_y + dy * 2), 2
            )

    def _draw_board(self) -> None:
        self.screen.blit(self.maze_bg, (0, 0))

        for row, col in self.sim.pellets:
            x = col * TILE_SIZE + TILE_SIZE // 2
            y = row * TILE_SIZE + TILE_SIZE // 2
            pygame.draw.circle(self.screen, WHITE, (x, y), 3)

        pulse = 7 + int((1 + math.sin(pygame.time.get_ticks() / 150)) )
        for row, col in self.sim.power_pellets:
            x = col * TILE_SIZE + TILE_SIZE // 2
            y = row * TILE_SIZE + TILE_SIZE // 2
            pygame.draw.circle(self.screen, WHITE, (x, y), pulse)

    # -- hud ------------------------------------------------------------

    def _draw_hud(self) -> None:
        top = self.board_height
        pygame.draw.rect(self.screen, BLACK, (0, top, self.width, HUD_HEIGHT))

        score = self.font.render(f"SCORE {self.sim.score}", True, YELLOW)
        self.screen.blit(score, (12, top + 8))

        status = f"{self.agent_label}  {self.difficulty.name}  seed {self.seed}"
        if self.sim.frightened():
            remaining = max(
                0.0, (self.sim.frightened_until_ms - self.sim.time_ms) / 1000.0
            )
            status += f"  POWER {remaining:.1f}s"
        status_surface = self.small_font.render(status, True, GREEN)
        self.screen.blit(
            status_surface,
            (self.width - status_surface.get_width() - 12, top + 14),
        )

        reason = getattr(self.sim.agent, "last_reason", "")
        reason_surface = self.small_font.render(str(reason)[:78], True, WHITE)
        self.screen.blit(reason_surface, (12, top + 36))

        keys = self.small_font.render(
            "SPACE pause    R restart    ESC quit", True, GREY
        )
        self.screen.blit(keys, (12, top + 55))

    def _draw_overlay(self) -> None:
        if not self.sim.game_over and not self.paused:
            return

        overlay = pygame.Surface((self.width, self.height), pygame.SRCALPHA)
        overlay.fill((0, 0, 0, 175))
        self.screen.blit(overlay, (0, 0))

        if self.paused and not self.sim.game_over:
            title, color, subtitle = "PAUSED", WHITE, "Press SPACE to resume"
        elif self.sim.win:
            title, color = "AGENT WINS", GREEN
            subtitle = f"performance {self.sim.performance():.0f}"
        else:
            title, color = "AGENT CAUGHT", RED
            subtitle = f"performance {self.sim.performance():.0f}"

        title_surface = self.font.render(title, True, color)
        subtitle_surface = self.small_font.render(subtitle, True, WHITE)
        self.screen.blit(
            title_surface,
            (self.width // 2 - title_surface.get_width() // 2, self.height // 2 - 26),
        )
        self.screen.blit(
            subtitle_surface,
            (self.width // 2 - subtitle_surface.get_width() // 2, self.height // 2 + 8),
        )

    # -- main loop ------------------------------------------------------

    def _handle_input(self) -> bool:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    return False
                if event.key == pygame.K_SPACE:
                    self.paused = not self.paused
                if event.key == pygame.K_r:
                    self.sim = self._new_simulation()
                    self.paused = False
        return True

    def run(self) -> None:
        running = True
        while running:
            elapsed = self.clock.tick(FPS)
            running = self._handle_input()

            if not self.paused and not self.sim.game_over:
                self.sim.advance(elapsed)

            self.screen.fill(BLACK)
            self._draw_board()
            self._draw_pacman(self.sim.player_progress())
            frightened = self.sim.frightened()
            for ghost in self.sim.ghosts:
                if ghost.released:
                    self._draw_ghost(ghost, self.sim.ghost_progress(), frightened)
                else:
                    self._draw_ghost(ghost, 1.0, False)
            self._draw_hud()
            self._draw_overlay()
            pygame.display.flip()

        pygame.quit()
