"""The task environment.

PROVIDED INFRASTRUCTURE. Do not edit this file.

This is the single authoritative implementation of the game rules. Both the
interactive window (``pacman/render.py``) and the headless trial runner
(``pacman/headless.py``) drive this same class, so what you watch on screen
and what gets scored in your trials obey identical rules.

Three things here are worth reading even though you will not modify them:

1. ``Simulation.sense`` builds the percept. It fills in exactly the fields
   your ``Percept`` dataclass declares and nothing else. If your agent
   cannot see something, it is because you did not ask for it.
2. ``Simulation.performance`` is the PERFORMANCE MEASURE. It is defined by
   the environment designer, not by the agent. Your agent's utility
   function is a separate thing that lives in ``agent.py``.
3. Collisions are resolved on whole tiles, including the case where
   Pac-Man and a ghost swap tiles. Your agent reasons in tile distances,
   so the rules and the agent's model agree.
"""

from __future__ import annotations

import dataclasses
import random
from collections import deque
from typing import Any, Iterable, Protocol

from .entities import Ghost, PacMan
from .maze import DIRECTIONS, LEVEL, MazeModel

PLAYER_PERIOD_MS = 135
GHOST_PERIOD_MS = 135
POWER_DURATION_MS = 2000

PELLET_POINTS = 10
POWER_PELLET_POINTS = 50
GHOST_CAPTURE_POINTS = 200

WIN_BONUS = 2000.0
CAUGHT_PENALTY = 1000.0
DECISION_COST = 0.20
BACKTRACK_COST = 2.0

GHOST_CHASE_PROBABILITY = 0.80
GHOST_RESPAWN_DELAY_MS = 2500


@dataclasses.dataclass(frozen=True)
class Difficulty:
    """A named task-environment setting.

    ``normal`` is what the assignment is graded on. ``hard`` exists so you
    have evidence for the write-up question about rationality: a correct,
    rational agent still loses some episodes there, because the ghosts are
    stochastic and the agent is not omniscient.
    """

    name: str
    level: tuple[str, ...]
    ghost_period_ms: int
    chase_probability: float


DIFFICULTIES: dict[str, Difficulty] = {
    # normal: ghosts move at exactly Pac-Man's speed.
    "normal": Difficulty("normal", LEVEL, 135, 0.80),
    # hard: ghosts move faster than Pac-Man, so outrunning them stops
    # working and only good routing keeps the agent alive.
    "hard": Difficulty("hard", LEVEL, 110, 0.80),
}

PACMAN_COLOR = (255, 230, 0)
GHOST_COLORS = [(245, 70, 55), (60, 220, 255), (255, 185, 220), (255, 155, 45)]
GHOST_RELEASE_DELAYS_MS = [0, 400, 800, 1200]


class Agent(Protocol):
    """What every agent in this assignment must provide."""

    percept_class: type
    last_reason: str

    def choose_action(self, percept: Any) -> tuple[int, int]:
        ...


class Simulation:
    """One episode of Pac-Man.

    Time is measured in milliseconds. Pac-Man acts every
    ``PLAYER_PERIOD_MS``; ghosts act every ``GHOST_PERIOD_MS``. Nothing is
    frame-rate dependent, so a run with a given seed produces the same
    outcome on every machine.
    """

    def __init__(
        self,
        maze: MazeModel,
        agent: Agent,
        seed: int = 0,
        ghost_period_ms: int = GHOST_PERIOD_MS,
        chase_probability: float = GHOST_CHASE_PROBABILITY,
    ):
        self.maze = maze
        self.agent = agent
        self.rng = random.Random(seed)
        self.seed = seed
        self.ghost_period_ms = ghost_period_ms
        self.chase_probability = chase_probability

        self.pellets: set[tuple[int, int]] = set(maze.pellet_start)
        self.power_pellets: set[tuple[int, int]] = set(maze.power_pellet_start)

        start_row, start_col = maze.player_start
        self.player = PacMan(start_row, start_col, PACMAN_COLOR)
        self.player.direction = DIRECTIONS["LEFT"]

        self.ghosts: list[Ghost] = []
        for index, (row, col) in maze.ghost_starts:
            self.ghosts.append(
                Ghost(
                    row,
                    col,
                    GHOST_COLORS[index % len(GHOST_COLORS)],
                    GHOST_RELEASE_DELAYS_MS[index % len(GHOST_RELEASE_DELAYS_MS)],
                )
            )

        self.time_ms = 0
        self.next_player_ms = PLAYER_PERIOD_MS
        self.next_ghost_ms = ghost_period_ms
        self.frightened_until_ms = 0

        self.score = 0
        self.game_over = False
        self.win = False

        # Statistics used by the performance measure and the trial report.
        self.decisions = 0
        self.visit_counts: dict[tuple[int, int], int] = {self.player.position: 1}
        self.immediate_backtracks = 0
        self.ghosts_eaten = 0
        self._position_two_steps_ago: tuple[int, int] | None = None

        self._door_target = self._compute_door_target()
        self._house_tiles = self._compute_house_tiles()

    # -- percept construction -----------------------------------------

    #: Every sensor reading this environment is able to report.
    SENSOR_FIELDS = (
        "player",
        "current_direction",
        "pellets",
        "power_pellets",
        "ghosts",
        "released_ghosts",
        "legal_actions",
        "frightened_time_remaining",
    )

    def sensor_readings(self) -> dict[str, Any]:
        return {
            "player": self.player.position,
            "current_direction": self.player.direction,
            "pellets": frozenset(self.pellets),
            "power_pellets": frozenset(self.power_pellets),
            "ghosts": tuple(ghost.position for ghost in self.ghosts),
            "released_ghosts": tuple(
                ghost.position for ghost in self.ghosts if ghost.released
            ),
            "legal_actions": self.maze.legal_actions_from(self.player.position),
            "frightened_time_remaining": max(
                0.0, (self.frightened_until_ms - self.time_ms) / 1000.0
            ),
        }

    def sense(self) -> Any:
        """Build a percept containing exactly the fields the agent declared."""
        percept_class = getattr(self.agent, "percept_class", None)
        if percept_class is None or not dataclasses.is_dataclass(percept_class):
            raise TypeError(
                f"{type(self.agent).__name__} must expose a 'percept_class' "
                "attribute referring to a dataclass."
            )

        available = self.sensor_readings()
        declared = [field.name for field in dataclasses.fields(percept_class)]

        unknown = [name for name in declared if name not in available]
        if unknown:
            raise ValueError(
                f"{percept_class.__name__} declares field(s) {unknown} that this "
                f"environment cannot sense. Available sensor fields are: "
                f"{list(self.SENSOR_FIELDS)}."
            )

        return percept_class(**{name: available[name] for name in declared})

    # -- performance measure -------------------------------------------

    def performance(self) -> float:
        """The externally imposed performance measure (AIMA 4e Sec. 2.2).

        This is not the agent's utility function. The agent may use whatever
        internal preferences it likes; this number is how the environment
        designer judges the resulting behaviour.
        """
        total = float(self.score)
        if self.win:
            total += WIN_BONUS
        if self.game_over and not self.win:
            total -= CAUGHT_PENALTY
        total -= DECISION_COST * self.decisions
        total -= BACKTRACK_COST * self.immediate_backtracks
        return round(total, 3)

    def outcome(self) -> str:
        if self.win:
            return "win"
        if self.game_over:
            return "caught"
        return "timeout"

    def report(self) -> dict[str, Any]:
        repeat_visits = sum(max(0, count - 1) for count in self.visit_counts.values())
        return {
            "seed": self.seed,
            "outcome": self.outcome(),
            "score": self.score,
            "decisions": self.decisions,
            "elapsed_seconds": round(self.time_ms / 1000.0, 3),
            "pellets_left": len(self.pellets) + len(self.power_pellets),
            "ghosts_eaten": self.ghosts_eaten,
            "repeat_visits": repeat_visits,
            "immediate_backtracks": self.immediate_backtracks,
            "performance": self.performance(),
        }

    # -- clock ----------------------------------------------------------

    def frightened(self) -> bool:
        return self.time_ms < self.frightened_until_ms

    def player_progress(self) -> float:
        """0.0 to 1.0 through the current Pac-Man move, for rendering only."""
        remaining = self.next_player_ms - self.time_ms
        return min(1.0, max(0.0, 1.0 - remaining / PLAYER_PERIOD_MS))

    def ghost_progress(self) -> float:
        remaining = self.next_ghost_ms - self.time_ms
        return min(1.0, max(0.0, 1.0 - remaining / self.ghost_period_ms))

    def advance(self, elapsed_ms: int) -> None:
        """Advance the clock, running every tick that falls due."""
        target = self.time_ms + elapsed_ms
        while not self.game_over:
            next_event = min(self.next_player_ms, self.next_ghost_ms)
            if next_event > target:
                break
            self._run_tick(next_event)
        if not self.game_over:
            self.time_ms = target

    def advance_one_tick(self) -> None:
        """Jump straight to the next scheduled tick. Used by trial runs."""
        if self.game_over:
            return
        self._run_tick(min(self.next_player_ms, self.next_ghost_ms))

    def _run_tick(self, event_time: int) -> None:
        self.time_ms = event_time
        player_due = self.next_player_ms == event_time
        ghosts_due = self.next_ghost_ms == event_time

        player_before = self.player.position
        ghosts_before = {id(ghost): ghost.position for ghost in self.ghosts}

        if player_due:
            self._step_player()
            self.next_player_ms += PLAYER_PERIOD_MS
        if ghosts_due and not self.game_over:
            self._step_ghosts()
            self.next_ghost_ms += self.ghost_period_ms

        if not self.game_over:
            self._resolve_collisions(player_before, ghosts_before)

    # -- agent turn -----------------------------------------------------

    def _step_player(self) -> None:
        percept = self.sense()
        legal = self.maze.legal_actions_from(self.player.position)
        action = self.agent.choose_action(percept)
        self.decisions += 1

        position_before = self.player.position

        if action in legal:
            self._move(self.player, action)

        position_after = self.player.position

        if position_after == self._position_two_steps_ago:
            self.immediate_backtracks += 1
        self._position_two_steps_ago = position_before

        self.visit_counts[position_after] = self.visit_counts.get(position_after, 0) + 1

        if position_after in self.pellets:
            self.pellets.remove(position_after)
            self.score += PELLET_POINTS
        if position_after in self.power_pellets:
            self.power_pellets.remove(position_after)
            self.score += POWER_PELLET_POINTS
            self.frightened_until_ms = self.time_ms + POWER_DURATION_MS

        if not self.pellets and not self.power_pellets:
            self.win = True
            self.game_over = True

    def _move(self, entity: Any, action: tuple[int, int]) -> None:
        entity.prev_row, entity.prev_col = entity.row, entity.col
        entity.row, entity.col = self.maze.step(entity.position, action)
        entity.direction = action

    # -- ghost turn -----------------------------------------------------

    def _compute_door_target(self) -> tuple[int, int] | None:
        if not self.maze.door_tiles:
            return None
        return min(self.maze.door_tiles)

    def _compute_house_tiles(self) -> frozenset[tuple[int, int]]:
        """Tiles inside the ghost house pen, found by flooding out from the
        ghost start tiles without crossing the door. Deriving this from the
        maze (rather than guessing at a row/column radius around the door)
        keeps it correct regardless of the pen's shape or size."""
        starts = {position for _, position in self.maze.ghost_starts}
        visited: set[tuple[int, int]] = set(starts)
        queue: deque[tuple[int, int]] = deque(starts)
        while queue:
            position = queue.popleft()
            for next_position, _ in self.maze.neighbors(position, allow_house_door=False):
                if next_position not in visited:
                    visited.add(next_position)
                    queue.append(next_position)
        return frozenset(visited)

    def _release_ghosts(self) -> None:
        for ghost in self.ghosts:
            if not ghost.released and self.time_ms >= ghost.release_delay_ms:
                ghost.released = True

    def _ghost_house_exit_action(self, ghost: Ghost) -> tuple[int, int]:
        if self._door_target is None:
            return DIRECTIONS["UP"]
        door_row, door_col = self._door_target
        if ghost.col < door_col:
            return DIRECTIONS["RIGHT"]
        if ghost.col > door_col:
            return DIRECTIONS["LEFT"]
        return DIRECTIONS["UP"]

    def _manhattan_after(self, ghost: Ghost, action: tuple[int, int]) -> int:
        row, col = self.maze.step(ghost.position, action)
        return abs(row - self.player.row) + abs(col - self.player.col)

    def _choose_ghost_action(self, ghost: Ghost) -> tuple[int, int]:
        if not ghost.released:
            return (0, 0)

        if self._door_target is not None and ghost.position in self._house_tiles:
            action = self._ghost_house_exit_action(ghost)
            if action in self.maze.legal_actions_from(
                ghost.position, allow_house_door=True
            ):
                return action

        valid = list(self.maze.legal_actions_from(ghost.position))
        if not valid:
            return (0, 0)

        reverse = (-ghost.direction[0], -ghost.direction[1])
        forward = [action for action in valid if action != reverse]
        if forward:
            valid = forward

        if self.frightened():
            return max(valid, key=lambda action: self._manhattan_after(ghost, action))

        # Stochastic: mostly chase, sometimes wander. This is what makes the
        # environment nondeterministic, so a rational choice can still lose.
        if self.rng.random() < self.chase_probability:
            return min(valid, key=lambda action: self._manhattan_after(ghost, action))
        return self.rng.choice(valid)

    def _step_ghosts(self) -> None:
        self._release_ghosts()
        for ghost in self.ghosts:
            if not ghost.released:
                continue
            action = self._choose_ghost_action(ghost)
            if action == (0, 0):
                continue
            next_row, next_col = self.maze.step(ghost.position, action)
            allow_door = self.maze.is_ghost_door(next_row, next_col)
            if action in self.maze.legal_actions_from(
                ghost.position, allow_house_door=allow_door
            ):
                self._move(ghost, action)

    def _respawn(self, ghost: Ghost) -> None:
        ghost.row, ghost.col = ghost.spawn
        ghost.prev_row, ghost.prev_col = ghost.spawn
        ghost.released = False
        ghost.direction = DIRECTIONS["UP"]
        ghost.release_delay_ms = self.time_ms + GHOST_RESPAWN_DELAY_MS

    def _resolve_collisions(
        self,
        player_before: tuple[int, int],
        ghosts_before: dict[int, tuple[int, int]],
    ) -> None:
        for ghost in self.ghosts:
            if not ghost.released:
                continue

            same_tile = ghost.position == self.player.position
            swapped = (
                ghost.position == player_before
                and self.player.position == ghosts_before.get(id(ghost))
            )
            if not same_tile and not swapped:
                continue

            if self.frightened():
                self.score += GHOST_CAPTURE_POINTS
                self.ghosts_eaten += 1
                self._respawn(ghost)
            else:
                self.game_over = True
                self.win = False
                return
