#!/usr/bin/env python3
"""Watch an agent play in a window.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Examples:
    python tools/play.py --agent utility_based
    python tools/play.py --agent model_based --seed 7
    python tools/play.py --agent greedy                 # external baseline
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.maze import MazeModel           # noqa: E402
from pacman.rules import DIFFICULTIES        # noqa: E402
from pacman.registry import BUILTIN_AGENTS, STUDENT_PARTS, resolve_agents  # noqa: E402

ALL_AGENT_NAMES = sorted(set(BUILTIN_AGENTS) | set(STUDENT_PARTS))


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the Pac-Man agent demo.")
    parser.add_argument(
        "--agent",
        default="utility_based",
        choices=ALL_AGENT_NAMES,
        help="which agent to run (default: utility_based)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="ghost randomness seed; the same seed always replays identically",
    )
    parser.add_argument(
        "--difficulty",
        default="normal",
        choices=sorted(DIFFICULTIES),
        help="normal is what you are graded on; on hard the ghosts move faster than you",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="directory containing your six *_agent.py files",
    )
    args = parser.parse_args()

    try:
        agents = resolve_agents([args.agent], args.project_root)
    except (ValueError, FileNotFoundError, AttributeError) as error:
        parser.error(str(error))

    try:
        from pacman.render import Window
    except ImportError:
        print(
            "Pygame is not installed. Install it with:\n"
            "    python -m pip install -r requirements.txt\n"
            "You can still run tools/run_trials.py without it.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    difficulty = DIFFICULTIES[args.difficulty]
    Window(
        agent_factory=agents[args.agent],
        agent_label=args.agent,
        seed=args.seed,
        maze=MazeModel(difficulty.level),
        difficulty=difficulty,
    ).run()


if __name__ == "__main__":
    main()
