#!/usr/bin/env python3
"""Compare agents over a shared set of seeds. No window, no Pygame needed.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Example:
    python tools/run_trials.py --count 30
    python tools/run_trials.py --agents utility_based,goal_based,greedy --count 30
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.headless import (   # noqa: E402
    SUMMARY_COLUMNS,
    TRIAL_COLUMNS,
    format_summary_table,
    run_trials,
    summarize,
    write_csv,
)
from pacman.rules import DIFFICULTIES        # noqa: E402
from pacman.registry import STUDENT_PARTS, resolve_agents  # noqa: E402

DEFAULT_AGENTS = ",".join(
    [*STUDENT_PARTS.keys(), "greedy", "random"]
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Paired-seed agent comparison.")
    parser.add_argument(
        "--agents",
        default=DEFAULT_AGENTS,
        help=f"comma-separated agent names (default: {DEFAULT_AGENTS})",
    )
    parser.add_argument("--count", type=int, default=30, help="number of seeds")
    parser.add_argument(
        "--difficulty",
        default="normal",
        choices=sorted(DIFFICULTIES),
        help="normal is what you are graded on; on hard the ghosts move faster than you",
    )
    parser.add_argument("--seed-start", type=int, default=1)
    parser.add_argument("--max-decisions", type=int, default=1500)
    parser.add_argument("--max-time-ms", type=int, default=240_000)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="directory containing your six *_agent.py files",
    )
    parser.add_argument(
        "--output", type=Path, default=PROJECT_ROOT / "results" / "trials.csv"
    )
    parser.add_argument(
        "--summary", type=Path, default=PROJECT_ROOT / "results" / "summary.csv"
    )
    args = parser.parse_args()

    try:
        agents = resolve_agents(args.agents.split(","), args.project_root)
    except (ValueError, FileNotFoundError, AttributeError) as error:
        parser.error(str(error))

    if not agents:
        parser.error("No agents selected.")

    seeds = list(range(args.seed_start, args.seed_start + args.count))

    try:
        rows = run_trials(
            agents,
            seeds,
            difficulty=args.difficulty,
            max_decisions=args.max_decisions,
            max_time_ms=args.max_time_ms,
        )
    except NotImplementedError as error:
        print(
            f"One of your agents raised NotImplementedError: {error}\n"
            "Finish the TODOs in that part's file, then rerun.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    summaries = summarize(rows)
    write_csv(args.output, rows, TRIAL_COLUMNS)
    write_csv(args.summary, summaries, SUMMARY_COLUMNS)

    print(format_summary_table(summaries))
    print()
    print(f"per-trial rows -> {args.output}")
    print(f"summary rows   -> {args.summary}")


if __name__ == "__main__":
    main()
