#!/usr/bin/env python3
"""Train the Part 6 learning agent.

PROVIDED INFRASTRUCTURE. Do not edit this file.

This is the "problem generator drives episodes, the critic judges them"
loop from AIMA 4e Figure 2.15. Each generation:

    1. ask the agent's problem generator for a candidate weight set
       (``propose_new_weights``)
    2. try it for a few training episodes
    3. hand the resulting mean performance to the critic/learning element
       (``learn``), which decides whether to keep it

None of that logic lives here -- this script only drives the loop and
reports what happened. ``learn`` and ``propose_new_weights`` are the two
things you implement in ``learning_agent.py``.

Example:
    python tools/train_learning_agent.py --generations 80
"""

from __future__ import annotations

import argparse
import json
import random
import statistics
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pacman.headless import run_episode          # noqa: E402
from pacman.maze import MazeModel                 # noqa: E402
from pacman.rules import DIFFICULTIES             # noqa: E402
from pacman.registry import load_student_agent    # noqa: E402


def evaluate(agent_factory, maze, difficulty, seeds) -> float:
    """Mean performance over ``seeds``, each with a FRESH agent instance so
    internal state from one episode never leaks into the next."""
    scores = [
        run_episode(agent_factory, seed, maze, difficulty)["performance"]
        for seed in seeds
    ]
    return statistics.fmean(scores)


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the Part 6 learning agent.")
    parser.add_argument("--generations", type=int, default=80)
    parser.add_argument(
        "--train-seeds",
        type=int,
        default=4,
        help="training episodes averaged per generation's performance judgement",
    )
    parser.add_argument("--eval-seeds", type=int, default=20)
    parser.add_argument("--seed", type=int, default=0, help="RNG seed for training")
    parser.add_argument("--difficulty", default="normal", choices=sorted(DIFFICULTIES))
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="directory containing your six *_agent.py files",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "results" / "learned_weights.json",
    )
    args = parser.parse_args()

    try:
        learning_factory = load_student_agent("learning", args.project_root)
    except (ValueError, FileNotFoundError, AttributeError) as error:
        parser.error(str(error))
        return

    # utility_based_agent.py is on sys.path now (load_student_agent put the
    # project root there); import it directly so we can build fresh,
    # state-free evaluation instances for a given set of weights.
    from utility_based_agent import UtilityBasedAgent

    def with_weights(weights):
        def factory(maze):
            fresh = UtilityBasedAgent(maze)
            fresh.weights = weights
            return fresh
        return factory

    difficulty = DIFFICULTIES[args.difficulty]
    maze = MazeModel(difficulty.level)

    agent = learning_factory(maze)  # the one persistent LearningAgent
    agent.rng = random.Random(args.seed)

    train_seeds_pool = list(range(1, 2000))
    eval_seeds = list(range(9001, 9001 + args.eval_seeds))

    start_weights = agent.weights
    start_score = evaluate(with_weights(start_weights), maze, difficulty, eval_seeds)

    print(f"Before training: mean performance over {len(eval_seeds)} held-out "
          f"seeds = {start_score:.1f}")
    print(f"Training for {args.generations} generations "
          f"({args.train_seeds} episode(s) averaged each)...")

    checkpoint = max(1, args.generations // 10)
    for generation in range(args.generations):
        candidate = agent.propose_new_weights()
        agent.performance_element.weights = candidate

        train_seeds = [
            train_seeds_pool[(generation * args.train_seeds + i) % len(train_seeds_pool)]
            for i in range(args.train_seeds)
        ]
        performance = evaluate(with_weights(candidate), maze, difficulty, train_seeds)
        agent.learn(performance)

        if (generation + 1) % checkpoint == 0:
            print(
                f"  generation {generation + 1:>4} | this try = {performance:8.1f} | "
                f"best so far = {agent.best_performance:8.1f}"
            )

    final_score = evaluate(with_weights(agent.best_weights), maze, difficulty, eval_seeds)

    print()
    print(f"After training:  mean performance over {len(eval_seeds)} held-out "
          f"seeds = {final_score:.1f}")
    print(f"Episodes trained on: {agent.episodes_seen}")
    print(f"Improvement: {final_score - start_score:+.1f}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "start_weights": _as_dict(start_weights),
        "best_weights": _as_dict(agent.best_weights),
        "eval_seeds": eval_seeds,
        "mean_performance_before": round(start_score, 3),
        "mean_performance_after": round(final_score, 3),
        "episodes_trained": agent.episodes_seen,
    }
    args.output.write_text(json.dumps(payload, indent=2))
    print(f"\nSaved -> {args.output}")


def _as_dict(weights) -> dict:
    return {name: getattr(weights, name) for name in weights.__dataclass_fields__}


if __name__ == "__main__":
    main()
