"""Greedy food-seeking baseline.

PROVIDED INFRASTRUCTURE. Do not edit this file.

This is deliberately NOT a correct answer to any of the six parts you build
in this project. It senses only its own position and the food, walks toward
the nearest pellet, and is completely blind to ghosts. It exists purely as a
weak external control for your trial comparisons -- every part you build
should beat it by a wide margin on 'normal' difficulty, and if one of yours
does not, that is a sign something in that part is still broken.

Do not read this file as a template for Part 2 (simple reflex). A simple
reflex agent reacts to condition-action RULES over the whole percept it is
given, including ghosts and frightened mode. This agent has neither; it is
closer to the naive starting point AIMA uses before introducing any of the
agent designs in Section 2.4.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..maze import DIRECTION_NAMES, MazeModel


@dataclass(frozen=True)
class GreedyPercept:
    player: tuple[int, int]
    pellets: frozenset[tuple[int, int]]
    power_pellets: frozenset[tuple[int, int]]
    legal_actions: tuple[tuple[int, int], ...]


class GreedyBaselineAgent:
    percept_class = GreedyPercept

    def __init__(self, maze: MazeModel):
        self.maze = maze
        self.last_reason = "Waiting for first percept."

    def choose_action(self, percept: GreedyPercept) -> tuple[int, int]:
        if not percept.legal_actions:
            self.last_reason = "No legal move."
            return (0, 0)

        food = set(percept.pellets) | set(percept.power_pellets)
        best_action = percept.legal_actions[0]
        best_distance = None

        for action in percept.legal_actions:
            landing = self.maze.step(percept.player, action)
            distance = self.maze.distance(landing, food)
            if best_distance is None or distance < best_distance:
                best_distance = distance
                best_action = action

        self.last_reason = (
            f"{DIRECTION_NAMES[best_action]} | greedy food-distance={best_distance}"
        )
        return best_action
