"""Random agent: the control condition.

PROVIDED INFRASTRUCTURE. Do not edit this file.

Notice how little it declares in its percept. The environment supplies only
the fields a percept class asks for, so this agent is genuinely blind to
ghosts, pellets, and frightened mode.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from ..maze import DIRECTION_NAMES, MazeModel


@dataclass(frozen=True)
class RandomPercept:
    legal_actions: tuple[tuple[int, int], ...]


class RandomAgent:
    percept_class = RandomPercept

    def __init__(self, maze: MazeModel, seed: int = 0):
        self.maze = maze
        self.rng = random.Random(seed)
        self.last_reason = "Waiting for first percept."

    def choose_action(self, percept: RandomPercept) -> tuple[int, int]:
        if not percept.legal_actions:
            self.last_reason = "No legal move."
            return (0, 0)

        action = self.rng.choice(percept.legal_actions)
        self.last_reason = f"{DIRECTION_NAMES[action]} | uniform random"
        return action
